apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: agents-service-hpa
  namespace: agents-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: agents-service
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 65
