apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../namespaces
- ../../rbac
- ../../config
- ../../agents
- ../../simulation
- ../../frontend
- ../../supporting
- ../../networkpolicies
namespace: agents-ns
patches:
- target:
    kind: Deployment
    name: agents-service
  patch: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: agents-service
    spec:
      replicas: 2
- target:
    kind: Deployment
    name: web-frontend
  patch: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: web-frontend
    spec:
      replicas: 1
- target:
    kind: Deployment
    name: llm-proxy
  patch: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: llm-proxy
    spec:
      replicas: 1
